Fix indexing error handling timestamp conversions
If we find a timestamp for a JSON document that is before the start of
the run, we first consider it to be a delta timestamp instead of an
absolute timestamp.

However, we were using the original value that was not converted to a
float to calculate the timestamp, this results in an error when that
value was a string:

```
   2019-01-29T14:13:14-UTC: Starting /pbench/archive/fs-version-001/b06-h31-1029p/TO-INDEX/fio_glusterfs-HDD-12GBper-pod-write_bs_4_2019.01.09T23.44.52.tar.xz (size 47584728)
        done templates (end ts: 2019-01-29T14:13:40-UTC, duration: 2.56s, successes: 3, retries: 0)
Other error unsupported type for timedelta microseconds component: str
Traceback (most recent call last):
  File "/opt/pbench-server/bin/index-pbench", line 2305, in main
    res = es_index(es, actions, fp, dbg=_DEBUG)
  File "/opt/pbench-server/lib/pbench/__init__.py", line 224, in es_index
    for ok, resp_payload in streaming_bulk_generator:
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/elasticsearch1/helpers/__init__.py", line 159, in streaming_bulk
    for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/elasticsearch1/helpers/__init__.py", line 53, in _chunk_actions
    for action, data in actions:
  File "/opt/pbench-server/lib/pbench/__init__.py", line 185, in actions_tracking_closure
    for cl_action in cl_actions:
  File "/opt/pbench-server/bin/index-pbench", line 2044, in make_all_actions
    for action in mk_tool_data_actions(ptb, options, idx_prefix, idx_patterns, opctx):
  File "/opt/pbench-server/bin/index-pbench", line 1565, in mk_tool_data_actions
    for source, source_id in asource:
  File "/opt/pbench-server/bin/index-pbench", line 1157, in _make_source_individual
    ts_val = self.mk_abs_timestamp_millis(val)
  File "/opt/pbench-server/bin/index-pbench", line 273, in mk_abs_timestamp_millis
    d = timedelta(0, 0, orig_ts * 1000)
TypeError: unsupported type for timedelta microseconds component: str
```

We use `orig_ts_float` instead which is already the expected value to
manipulate.

We also enhance the error handling so that we can see what happened for
a given exception.