Update to `black` 22.3.0
Recently (4 hours ago at the time of this PR creation), `click` 8.1.0
was released on PyPI.org.  But that caused our CI jobs to fail with
the following:

```
py run-test: commands[0] | black --check .
Traceback (most recent call last):
  File "/var/tmp/jenkins/tox/py/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "src/black/__init__.py", line 1423, in patched_main
  File "src/black/__init__.py", line 1409, in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (/var/tmp/jenkins/tox/py/lib/python3.9/site-packages/click/__init__.py)
ERROR: InvocationError for command /var/tmp/jenkins/tox/py/bin/black --check . (exited with code 1)
```

The fix is updating to `black` to 22.3.0.