Refactor to fix trafficgen UIDs
The `pbench-trafficgen` script generates unique iterations based on the
following command line argument (provided or defaulted):

 * `--traffic-profiles`
 * `--rates`
 * `--traffic-directions`
 * `--frame-sizes`
 * `--num-flows`
 * `--max-loss-pcts`

However, the UIDs for each generated sample was using the following set
of data:

 * `-traffic_generator:%traffic_generator%-trial:%trial%`

This can lead to situations where one asks for `pbench-trafficgen` to
run multiple iterations, where if the trial numbers don't match the
iteration data won't be merged.

This set of modifications ensures that the UIDs used in the generated
data match the values used to create each iteration.

One of the behaviors observed previously was that one could see an
error like the following (long lines artificially wrapped):

```
Error: values do not match
key: claimed_dev_pairs values: ARRAY(0x559b88b50c20) \
  ARRAY(0x559b88b5f750)
Error: values do not match
key: null_stats values: HASH(0x559b88b5d230) HASH(0x559b88b5df68)
Error: values do not match
key: output_dir values: \
  /var/lib/pbench-agent/\
    trafficgen_RHOSP16.1-RHEL8.2-OVS-OFFLOAD\
      _tg:trex_r:none_fs:1500_nf:128_fm:si_td:bi_ml:0.002_tt:bs_\
      _2021-01-13T10:43:04/\
    1-bidirectional-1500B-128flows-0.002pct_drop/sample2 \
  /var/lib/pbench-agent/\
    trafficgen_RHOSP16.1-RHEL8.2-OVS-OFFLOAD\
      _tg:trex_r:none_fs:1500_nf:128_fm:si_td:bi_ml:0.002_tt:bs_\
      _2021-01-13T10:43:04/\
    1-bidirectional-1500B-128flows-0.002pct_drop/sample3
Error: values do not match
key: test_dev_pairs values: ARRAY(0x559b88b5d500) ARRAY(0x559b88b5f498)
```

This output was due in part to the UIDs not matching because the `trial`
value was different.  But even if we resolve that difference, the
`output_dir` key will always be different between samples, causing this
error to be emitted.  Further, differences between Perl arrays and
hashes were not being handled properly, causing the other errors
emtited above.

This change addresses those problems as well.

Finally, we handle the behavior of the `--postprocess-only` mode where
we ensure that files are not overwritten unexpectedly.