flake8: fix flake8 errors
server/lib/pbench/indexer.py:9:1: F401 'stat' imported but unused
server/lib/pbench/indexer.py:29:1: F401 'urllib3.exceptions as ul_excs' imported but unused
server/lib/pbench/indexer.py:39:5: F401 'elasticsearch.VERSION as es_VERSION' imported but unused
server/lib/pbench/indexer.py:2231:13: F402 import 'csv' from line 13 shadowed by loop variable
server/lib/pbench/indexer.py:2343:9: E306 expected 1 blank line before a nested definition, found 0
server/lib/pbench/indexer.py:2493:13: F402 import 'csv' from line 13 shadowed by loop variable
server/lib/pbench/indexer.py:2692:29: F811 redefinition of unused 'stat' from line 9
server/lib/pbench/indexer.py:3144:13: E741 ambiguous variable name 'l'
server/lib/pbench/indexer.py:3163:9: E741 ambiguous variable name 'l'

Signed-off-by: Chuck Short <chucks@redhat.com>