Fix flake8 in server/lib/pibench/indexer.py
./server/lib/pbench/indexer.py:9:1: F401 'stat' imported but unused
./server/lib/pbench/indexer.py:29:1: F401 'urllib3.exceptions as ul_excs' imported but unused
./server/lib/pbench/indexer.py:39:5: F401 'elasticsearch.VERSION as es_VERSION' imported but unused
./server/lib/pbench/indexer.py:2146:13: F402 import 'csv' from line 13 shadowed by loop variable
./server/lib/pbench/indexer.py:2258:9: E306 expected 1 blank line before a nested definition, found 0
./server/lib/pbench/indexer.py:2403:13: F402 import 'csv' from line 13 shadowed by loop variable
./server/lib/pbench/indexer.py:2600:29: F811 redefinition of unused 'stat' from line 9
./server/lib/pbench/indexer.py:3052:13: E741 ambiguous variable name 'l'
./server/lib/pbench/indexer.py:3071:9: E741 ambiguous variable name 'l'
./server/lib/pbench/indexer.py:3212:24: E721 do not compare types, use 'isinstance()'
./server/lib/pbench/indexer.py:3215:28: E721 do not compare types, use 'isinstance()'

Signed-off-by: Chuck Short <chucks@redhat.com>